version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/capstone-1

hooks:
  BeforeInstall:
    - location: infrastructure/scripts/install_node_pm2.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: infrastructure/scripts/start_pm2.sh
      timeout: 600
      runas: root
